on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |

          pip install -r requirements.txt
          pip install --upgrade pip 
      - name: Test
        run: |
          gunicorn -b 0.0.0.0:8080 --chdir controller/ app:app -w 4 & sleep 5
          python3 -m unittest tests/DataHandlerTest.py tests/maintestIntegration.py  tests/testDB.py
          curl http://localhost:8080/health
          kill $(jobs -p)


      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/TODO_LIST_APP/ &&
              git pull'